// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_mainPanel;
void ui_event_WtmpARC(lv_event_t * e);
extern lv_obj_t * ui_WtmpARC;
void ui_event_WtmpLabel(lv_event_t * e);
extern lv_obj_t * ui_WtmpLabel;
void ui_event_TmpLabel(lv_event_t * e);
extern lv_obj_t * ui_TmpLabel;
void ui_event_HmdLabel(lv_event_t * e);
extern lv_obj_t * ui_HmdLabel;
void ui_event_HeatButton(lv_event_t * e);
extern lv_obj_t * ui_HeatButton;
extern lv_obj_t * ui_Label10;
void ui_event_ProgButton(lv_event_t * e);
extern lv_obj_t * ui_ProgButton;
extern lv_obj_t * ui_ProgLabel;
void ui_event_wifiLabel(lv_event_t * e);
extern lv_obj_t * ui_wifiLabel;
void ui_event_serverlabel(lv_event_t * e);
extern lv_obj_t * ui_serverlabel;
void ui_event_TimeLabel(lv_event_t * e);
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_Label1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_ProgPanel;
void ui_event_wtmpSLider(lv_event_t * e);
extern lv_obj_t * ui_wtmpSLider;
extern lv_obj_t * ui_ProgTmpLabel;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label15;
void ui_event_Roller1(lv_event_t * e);
extern lv_obj_t * ui_Roller1;
void ui_event_Roller2(lv_event_t * e);
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_TmpChart;
extern lv_obj_t * ui_WTMPSliderLable;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_HeatPanel;
void ui_event_Back2Button(lv_event_t * e);
extern lv_obj_t * ui_Back2Button;
extern lv_obj_t * ui_Back2Label;
void ui_event_HeatSetting(lv_event_t * e);
extern lv_obj_t * ui_HeatSetting;
extern lv_obj_t * ui_HeatScreenLabel;
void ui_event_offsetSlider(lv_event_t * e);
extern lv_obj_t * ui_offsetSlider;
extern lv_obj_t * ui_offsetlabelText;
extern lv_obj_t * ui_offsetNumberLabel;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
