// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void set_WTMP(lv_event_t * e);
void get_Wtmp(lv_event_t * e);
void Set_Temp(lv_event_t * e);
void setting_Hmd(lv_event_t * e);
void WifiConneted(lv_event_t * e);
void ClientConneted(lv_event_t * e);
void setClock(lv_event_t * e);
void SetWantedTMPSCR2(lv_event_t * e);
void setProgNum(lv_event_t * e);
void setProgHour(lv_event_t * e);
void ChangeHeatSetting(lv_event_t * e);
void setoffsetNumber(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
