// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void set_WTMP(lv_event_t * e)
{
	// Your code here
  
}

void Set_Temp(lv_event_t * e)
{
	// Your code here
}

void setting_Hmd(lv_event_t * e)
{
	// Your code here
}

void WifiConneted(lv_event_t * e)
{
	// Your code here
}

void ClientConneted(lv_event_t * e)
{
	// Your code here
}

void setClock(lv_event_t * e)
{
	// Your code here
}

void get_Wtmp(lv_event_t * e)
{
	// Your code here
}

void setProgHour(lv_event_t * e)
{
	// Your code here
}

void getProgHour(lv_event_t * e)
{
	// Your code here
}

void setProgTmp(lv_event_t * e)
{
	// Your code here
}

void getProgHourTmp(lv_event_t * e)
{
	// Your code here
}

void setProgNumber(lv_event_t * e)
{
	// Your code here
}

void getNumber(lv_event_t * e)
{
	// Your code here
}

void ChangeHeatSetting(lv_event_t * e)
{
	// Your code here
}

void setProgNum(lv_event_t * e)
{
	// Your code here
}

void SetProgressBar(lv_event_t * e)
{
	// Your code here
}

void SetWantedTMPSCR2(lv_event_t * e)
{
	// Your code here
}

void setoffsetNumber(lv_event_t * e)
{
	// Your code here
}
