// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeatPanel = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_HeatPanel, 320);
    lv_obj_set_height(ui_HeatPanel, 240);
    lv_obj_set_align(ui_HeatPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HeatPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HeatPanel, lv_color_hex(0x06053E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeatPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back2Button = lv_btn_create(ui_HeatPanel);
    lv_obj_set_width(ui_Back2Button, 100);
    lv_obj_set_height(ui_Back2Button, 20);
    lv_obj_set_x(ui_Back2Button, 0);
    lv_obj_set_y(ui_Back2Button, 90);
    lv_obj_set_align(ui_Back2Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Back2Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Back2Label = lv_label_create(ui_HeatPanel);
    lv_obj_set_width(ui_Back2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Back2Label, 0);
    lv_obj_set_y(ui_Back2Label, 90);
    lv_obj_set_align(ui_Back2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Back2Label, "Back");

    ui_HeatSetting = lv_dropdown_create(ui_HeatPanel);
    lv_dropdown_set_options(ui_HeatSetting, "Auto Heater\nGas heater\n");
    lv_obj_set_width(ui_HeatSetting, 150);
    lv_obj_set_height(ui_HeatSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeatSetting, 0);
    lv_obj_set_y(ui_HeatSetting, -40);
    lv_obj_set_align(ui_HeatSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HeatSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_HeatScreenLabel = lv_label_create(ui_HeatPanel);
    lv_obj_set_width(ui_HeatScreenLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeatScreenLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeatScreenLabel, 0);
    lv_obj_set_y(ui_HeatScreenLabel, -90);
    lv_obj_set_align(ui_HeatScreenLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeatScreenLabel, "Heater settings");
    lv_obj_set_style_text_font(ui_HeatScreenLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_offsetSlider = lv_slider_create(ui_HeatPanel);
    lv_slider_set_range(ui_offsetSlider, -100, 100);
    lv_slider_set_value(ui_offsetSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_offsetSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_offsetSlider, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_offsetSlider, 150);
    lv_obj_set_height(ui_offsetSlider, 5);
    lv_obj_set_x(ui_offsetSlider, -20);
    lv_obj_set_y(ui_offsetSlider, 40);
    lv_obj_set_align(ui_offsetSlider, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_offsetSlider, lv_color_hex(0x19ACBA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_offsetSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_offsetlabelText = lv_label_create(ui_HeatPanel);
    lv_obj_set_width(ui_offsetlabelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_offsetlabelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_offsetlabelText, 0);
    lv_obj_set_y(ui_offsetlabelText, 15);
    lv_obj_set_align(ui_offsetlabelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_offsetlabelText, "Temperaure offset");
    lv_obj_set_style_text_font(ui_offsetlabelText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_offsetNumberLabel = lv_label_create(ui_HeatPanel);
    lv_obj_set_width(ui_offsetNumberLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_offsetNumberLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_offsetNumberLabel, 75);
    lv_obj_set_y(ui_offsetNumberLabel, 40);
    lv_obj_set_align(ui_offsetNumberLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_offsetNumberLabel, "0");

    lv_obj_add_event_cb(ui_Back2Button, ui_event_Back2Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HeatSetting, ui_event_HeatSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_offsetSlider, ui_event_offsetSlider, LV_EVENT_ALL, NULL);

}
