// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProgPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_ProgPanel, 320);
    lv_obj_set_height(ui_ProgPanel, 240);
    lv_obj_set_align(ui_ProgPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ProgPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ProgPanel, lv_color_hex(0x05063E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wtmpSLider = lv_slider_create(ui_ProgPanel);
    lv_slider_set_range(ui_wtmpSLider, 0, 350);
    lv_slider_set_value(ui_wtmpSLider, 200, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_wtmpSLider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_wtmpSLider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_wtmpSLider, 200);
    lv_obj_set_height(ui_wtmpSLider, 5);
    lv_obj_set_x(ui_wtmpSLider, -20);
    lv_obj_set_y(ui_wtmpSLider, -20);
    lv_obj_set_align(ui_wtmpSLider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_wtmpSLider, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wtmpSLider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_wtmpSLider, lv_color_hex(0x19ACBA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wtmpSLider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ProgTmpLabel = lv_label_create(ui_ProgPanel);
    lv_obj_set_width(ui_ProgTmpLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProgTmpLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProgTmpLabel, 0);
    lv_obj_set_y(ui_ProgTmpLabel, -40);
    lv_obj_set_align(ui_ProgTmpLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProgTmpLabel, "Wanted Temperature ");

    ui_Button3 = lv_btn_create(ui_ProgPanel);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 35);
    lv_obj_set_x(ui_Button3, 85);
    lv_obj_set_y(ui_Button3, -80);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_ProgPanel);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 85);
    lv_obj_set_y(ui_Label15, -80);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Back");

    ui_Roller1 = lv_roller_create(ui_ProgPanel);
    lv_roller_set_options(ui_Roller1, "prog 1\nprog 2\nprog 3\nprog 4\nprog 5\n", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller1, 45);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, -100);
    lv_obj_set_y(ui_Roller1, -80);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x2A2526), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Roller2 = lv_roller_create(ui_ProgPanel);
    lv_roller_set_options(ui_Roller2,
                          "0  am\n1  am\n2  am\n3  am\n4  am\n5  am\n6  am\n7  am\n8  am\n9  am\n10 am\n11 am\n12 pm\n13 pm\n14 pm\n15 pm\n16 pm\n17 pm\n18 pm\n19 pm\n20 pm\n21 pm\n22 pm\n23 pm",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Roller2, 12, LV_ANIM_OFF);
    lv_obj_set_height(ui_Roller2, 43);
    lv_obj_set_width(ui_Roller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller2, -15);
    lv_obj_set_y(ui_Roller2, -80);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0x2A2525), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_TmpChart = lv_chart_create(ui_ProgPanel);
    lv_obj_set_width(ui_TmpChart, 250);
    lv_obj_set_height(ui_TmpChart, 100);
    lv_obj_set_x(ui_TmpChart, 0);
    lv_obj_set_y(ui_TmpChart, 50);
    lv_obj_set_align(ui_TmpChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_TmpChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_TmpChart, 24);
    lv_chart_set_range(ui_TmpChart, LV_CHART_AXIS_PRIMARY_Y, 0, 350);
    lv_chart_set_range(ui_TmpChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_TmpChart, 10, 24);
    lv_chart_set_axis_tick(ui_TmpChart, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 0);
    lv_chart_set_axis_tick(ui_TmpChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 7, 1, false, 1);
    lv_chart_set_axis_tick(ui_TmpChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    /*lv_chart_series_t * ui_TmpChart_series_1 = lv_chart_add_series(ui_TmpChart, lv_color_hex(0x19ACBA),
                                                                   LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_TmpChart_series_1_array[] = { 10, 30, 20, 15, 20, 10, 35 };
    lv_chart_set_ext_y_array(ui_TmpChart, ui_TmpChart_series_1, ui_TmpChart_series_1_array);*/
    lv_obj_set_style_line_color(ui_TmpChart, lv_color_hex(0x5A3636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_TmpChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_TmpChart, lv_color_hex(0x19ACBA), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_TmpChart, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_TmpChart, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_TmpChart, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_TmpChart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TmpChart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_WTMPSliderLable = lv_label_create(ui_ProgPanel);
    lv_obj_set_width(ui_WTMPSliderLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTMPSliderLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WTMPSliderLable, 100);
    lv_obj_set_y(ui_WTMPSliderLable, -20);
    lv_obj_set_align(ui_WTMPSliderLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WTMPSliderLable, "20");
    lv_obj_set_style_text_font(ui_WTMPSliderLable, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_wtmpSLider, ui_event_wtmpSLider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Roller1, ui_event_Roller1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Roller2, ui_event_Roller2, LV_EVENT_ALL, NULL);

}
