// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_mainPanel, 320);
    lv_obj_set_height(ui_mainPanel, 240);
    lv_obj_set_align(ui_mainPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainPanel, lv_color_hex(0x05063E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WtmpARC = lv_arc_create(ui_mainPanel);
    lv_obj_set_width(ui_WtmpARC, 300);
    lv_obj_set_height(ui_WtmpARC, 200);
    lv_obj_set_x(ui_WtmpARC, 50);
    lv_obj_set_y(ui_WtmpARC, 20);
    lv_obj_set_align(ui_WtmpARC, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_WtmpARC, 0, 350);
    lv_arc_set_value(ui_WtmpARC, 215);
    lv_obj_set_style_arc_color(ui_WtmpARC, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_WtmpARC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_WtmpARC, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_WtmpARC, NULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_WtmpARC, lv_color_hex(0x19ACBA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_WtmpARC, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_WtmpARC, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WtmpLabel = lv_label_create(ui_WtmpARC);
    lv_obj_set_width(ui_WtmpLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WtmpLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WtmpLabel, -50);
    lv_obj_set_y(ui_WtmpLabel, -60);
    lv_obj_set_align(ui_WtmpLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WtmpLabel, "0 °C");
    lv_obj_set_style_text_font(ui_WtmpLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TmpLabel = lv_label_create(ui_WtmpARC);
    lv_obj_set_width(ui_TmpLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TmpLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TmpLabel, -50);
    lv_obj_set_y(ui_TmpLabel, -30);
    lv_obj_set_align(ui_TmpLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TmpLabel, "0 °C");
    lv_obj_set_style_text_font(ui_TmpLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HmdLabel = lv_label_create(ui_WtmpARC);
    lv_obj_set_width(ui_HmdLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HmdLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HmdLabel, -50);
    lv_obj_set_y(ui_HmdLabel, 0);
    lv_obj_set_align(ui_HmdLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HmdLabel, "0 %");

    ui_HeatButton = lv_btn_create(ui_WtmpARC);
    lv_obj_set_width(ui_HeatButton, 100);
    lv_obj_set_height(ui_HeatButton, 20);
    lv_obj_set_x(ui_HeatButton, -50);
    lv_obj_set_y(ui_HeatButton, 40);
    lv_obj_set_align(ui_HeatButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HeatButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HeatButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_HeatButton);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Heat option");

    ui_ProgButton = lv_btn_create(ui_WtmpARC);
    lv_obj_set_width(ui_ProgButton, 100);
    lv_obj_set_height(ui_ProgButton, 20);
    lv_obj_set_x(ui_ProgButton, -50);
    lv_obj_set_y(ui_ProgButton, 70);
    lv_obj_set_align(ui_ProgButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProgButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ProgButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProgLabel = lv_label_create(ui_ProgButton);
    lv_obj_set_width(ui_ProgLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProgLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ProgLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProgLabel, "Programs");

    ui_wifiLabel = lv_label_create(ui_mainPanel);
    lv_obj_set_width(ui_wifiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiLabel, -85);
    lv_obj_set_y(ui_wifiLabel, -100);
    lv_obj_set_align(ui_wifiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiLabel, "Disconneted");
    lv_obj_set_style_text_font(ui_wifiLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_serverlabel = lv_label_create(ui_mainPanel);
    lv_obj_set_width(ui_serverlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_serverlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_serverlabel, -110);
    lv_obj_set_y(ui_serverlabel, -70);
    lv_obj_set_align(ui_serverlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_serverlabel, "Client: 0");
    lv_obj_set_style_text_font(ui_serverlabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel = lv_label_create(ui_mainPanel);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, 100);
    lv_obj_set_y(ui_TimeLabel, -95);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "00:00");
    lv_obj_set_style_text_letter_space(ui_TimeLabel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TimeLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TimeLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 117);
    lv_obj_set_y(ui_Label1, -54);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "OFF");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WtmpLabel, ui_event_WtmpLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TmpLabel, ui_event_TmpLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HmdLabel, ui_event_HmdLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HeatButton, ui_event_HeatButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProgButton, ui_event_ProgButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WtmpARC, ui_event_WtmpARC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiLabel, ui_event_wifiLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_serverlabel, ui_event_serverlabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TimeLabel, ui_event_TimeLabel, LV_EVENT_ALL, NULL);

}
